# Generated by Django 5.1.5 on 2025-02-16 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='model',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
