# Generated by Django 5.1.5 on 2025-02-16 09:44

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequence',
            name='images',
            field=models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
    ]
